server {
    listen 80 default_server;
    root /var/www/html;
    index index.html index.htm;
    server_name _;

    location / {
        try_files $uri $uri/ =404;
        add_header X-Deployed-By "Ansible";
    }

    access_log /var/log/nginx/ansible_access.log;
    error_log /var/log/nginx/ansible_error.log;
}
